### ISSUE TITLE
Ready this transformer plugin for GraphQL Transformer v2

### ISSUE THREAD

**Issue by renebrandel** [flogy/graphql-retain-transformer#14]
👋  This is Rene from the AWS Amplify team! First off, **THANK YOU** for your amazing plugin! 

I have some great news to share, we've rewritten the GraphQL Transformer plugin from the ground up to take advantage of some really amazing capabilities. All the details here: https://github.com/aws-amplify/amplify-cli/issues/6217#issuecomment-929677992 

### How to migrate your plugin to GraphQL Transformer v2
In order to make this plugin forward compatible with GraphQL Transformer v2, you need to make some tiny adjustments to the classes you inherit from. Migration steps here: https://gist.github.com/renebrandel/0b9537e2016e3dd9ed6d794b30b2e3f4

Happy to also hop on a call with you to walk you through the process. Email me at any time: renbran at amazon dot com

**Comment by houmark** [comment]
Hey @renebrandel,

Just wanted to appreciate that you seem to be on top of things here 🙇. Excited to see that the Amplify finally seems to have a good lead where things seem better coordinated. We've been affected by so many issues in the past where coordination lacked so much that new features or attempted bug fixes just shifted the problem.

P.S. While this would retire this plugin, this really should be part of the Amplify core, but having it as a plugin is definitely better than not having this option. There is a slight annoyance with the use of plugins like this, where the Amplify Console needs the package installed, but the only way (that we are aware of) to install the plugin so it can do it's work is by including it in the project package.json and that means added run time and a bunch of unnecessary overhead. More here: #9 

I know you are not responsible for the Ampify Console, but maybe you know of a better way or could ping the Console team to have a look at how Amplify plugins that are needed for the build process only can be initiated/installed better?

**Comment by renebrandel** [comment]
Hi @houmark  - thanks for the pointers. While we can't automate the process in the short-term, I'm also trying to rewrite our docs to be more use case oriented. Happy to specifically call out the additional steps required on the documentation to reduce customer confusion in the short-term.

**Comment by flogy** [comment]
A new version of this transformer was released which is now compatible with GraphQL Transformer v2 🚀
