### ISSUE TITLE
Error occurred during the push operation:

### ISSUE THREAD

**Issue by tassiosouza** [flogy/graphql-retain-transformer#15]
Hello, I'm having this error after npm installed the lib and added the @retain directive to my model: 

An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
ctx.getResource is not a function

Here is what I have done: 

- run: npm install --save graphql-retain-transformer on the root folder of the project
- added:
 ```
"transformers": [
    "graphql-retain-transformer"
] 
```
to transform.conf.json: the file is like that now: 
```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    },
    "transformers": [
        "graphql-retain-transformer"
    ]
}
```

- Added the retain directive to my model in graphql schema, the model is like this: 
```
type Route @model @auth(rules: [{allow: public}]) @retain{
  id: ID!
  cost: Float
  startTime: AWSTimestamp
  endTime: AWSTimestamp
  status: RouteStatus
  name: String!
  orders: [MpsOrder] @hasMany(indexName: "byRoute", fields: ["id"])
  driver: Driver @hasOne
}
```

- run: amplify push dev

Error: 
✖ An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
ctx.getResource is not a function

What I've done wrong, anyone else got this error before ? 

Thank you!

**Comment by flogy** [comment]
Hi @tassiosouza 

Thanks for using this plugin. The error you've seen was because this plugin was not yet migrated to the latest GraphQL Transformer v2 version that is used by Amplify now. I have now migrated it for you so you can just update to the latest version and should be good to go 🙂

Please let me know if there are any more questions or else enjoy building with Amplify! Oh any please leave a star if you like the plugin ⭐️ Thanks!

Cheers,
Florian

**Comment by tassiosouza** [comment]
Thank you so much @flogy ! now I'm able to push to amplify. But I still have another problem related to use the plugin: 
- After pushed to amplify, when I changed my new models with new properties and click on deploy, I got this error message from amplify studio:

`Cannot find module '/root/.amplify/lib/node_modules/graphql-retain-transformer'. `

I'm sure I have it installed locally, because I was able to build locally. It seams that the installation was not pushed to the cloud, how can I install the plugin on remote ?

Btw, I got this message at the end of the amplify push dev command log (I was able to push, but this message was there): 
`Failed to create models in the cloud: Modelgen job creation failed`

Is there anything that I'm missing ? 

Thank you!

**Comment by flogy** [comment]
That is weird. You should not have to push the plugin to remote. The plugin only modifies the CloudFormation stack file locally, which is then used to setup the remote infrastructure.

Did you follow the installation instructions in the README precisely?

Could you share your code maybe and maybe a full error log?

**Comment by tassiosouza** [comment]
Hi @flogy, I think my problem is that amplify can not create the resources in the cloud after adding the @retain directive and the transformer plugin. The error I mentioned before is related to the amplify studio, let's not consider using it for now. 

When I run `amplify push dev`, everything in the log looks good except for the last error message that says: 

`failed to create models in the cloud: Modelgen job creation failed`

Even though I can see the model updated at the data modeling tab in amplify studio. The model is not really updated, because it does not show the new properties for the old data stored in the cloud, also if I try to create new data with the new properties and save it on the cloud, the data is saved successfully, but the new properties of this data is not shown on the content nor in the dynamodb database, probably because the models could not be generated in the cloud after adding the transform retain plugin. 

I have reverted the installation of the transform plugin and pushed again to amplify my new graphql schema, and at that time, the models were generated in the cloud with the new properties. In conclusion, the main problem is that amplify can not generate the models in the cloud (locally it works) after adding the transformer plugin. Once again, because the plugin was not pushed to the cloud with the amplify push command.

I have followed all the steps in the read me, as follow: 

- Installed the plugin running `npm install --save graphql-retain-transformer` in the project root folder
- Edited amplify/backend/api/mpsdriverapp/transform.conf.json and append "graphql-retain-transformer" to the transformers field. The code looks like this:

```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    },
    "transformers": [
        "graphql-retain-transformer"
    ]
}
```

- Added the retain directive to all my models like this: 
```
type Driver @model @auth(rules: [{allow: public}]) @retain {
  id: ID!
  name: String!
  email: String!
  phone: String
  carCapacity: Int
  owner: String!
  onBoard: Boolean
}
```

Please let me know if you want to inspect another part of my code. Thank you

**Comment by tassiosouza** [comment]
UPDATE: Don't we need to install the plugin by running `amplify plugin add` like described here: 
https://docs.amplify.aws/cli/plugins/plugins/#add

However when I try to add with the node_modules installation path of the plugin I get the error message: 
```
Failed to add the plugin package.
Error code: FailedVerification
Plugin verification error code: MissingManifest
```

I think this problem could be solved if we could successfully install the plugin to amplify and then push it to cloud, what do you think about that ?

**Comment by flogy** [comment]
That is weird. I have never tested the plugin together with Amplify Studio but according to [this chapter in the docs](https://docs.amplify.aws/cli/plugins/authoring/#adding-custom-graphql-transformers-to-the-project) the plugin installation should be alright. Your installation and usage of the plugin looks fine to me too. Not sure what this could be 🤔
