### ISSUE TITLE
Can you explain more what this does and why I might need to use it?

### ISSUE THREAD

**Issue by PeteDuncanson** [flogy/graphql-retain-transformer#8]
hi

I've been searching through Github for as many graphql transformers for AppSync (an AWS Amplify) as I can find and came across this. Is there any chance you can expand on the readme to give more context about what this actualy does, why might I want to use it, what the implications are etc.

It sounds like a think I might find useful but there is just not quite enough info to know for sure :)

Cheers

Pete

**Comment by flogy** [comment]
Hi @PeteDuncanson 

Thanks for creating this issue. Indeed, this could be explained in a few sentences on the README page. For now, you could read my blog post about the plugin, which explains in more detail what it is all about: https://react-freelancer.ch/blog/amplify-retain-dynamodb-tables

What do you think about just adding the second paragraph ("graphql-retain-transformer") to the README? Would this be the explanation you were looking for? Or is there any information missing?

Thanks for helping to make this plugin and the AWS Amplify community awesome 💯

**Comment by PeteDuncanson** [comment]
Oh that blog explains it well, now I get it :)

Yes I think a paragraph is all thats needed with maybe a link to that blog post if folks want to know more.

Thank you for publishing stuff like this :)
